// <auto-generated />
namespace UserRegistration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class registersucess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(registersucess));
        
        string IMigrationMetadata.Id
        {
            get { return "202212060934416_registersucess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
